name: "GammaCode GitHub Action"
description: "Run GammaCode AI assistant in GitHub Actions workflows"
branding:
  icon: "code"
  color: "orange"

inputs:
  api-key:
    description: "GammaCode API key for authentication (Pro subscription required). Get your API key from https://app.gammacode.dev/settings"
    required: true

  share:
    description: "Whether to share the GammaCode session. Defaults to true for public repositories."
    required: false
    default: "true"

  token:
    description: "Optional GitHub access token for performing operations such as creating comments, committing changes, and opening pull requests. Defaults to the installation access token from the GammaCode-IH GitHub App."
    required: false

runs:
  using: "composite"
  steps:
    - name: Install GammaCode
      shell: bash
      run: curl -fsSL https://github.com/Zenprenuers/GammaCode-Releases/releases/download/v1.0.15/install | bash

    - name: Install bun
      shell: bash
      run: npm install -g bun

    - name: Install dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Run GammaCode
      shell: bash
      run: bun ${GITHUB_ACTION_PATH}/index.ts
      env:
        GAMMACODE_API_KEY: ${{ inputs.api-key }}
        SHARE: ${{ inputs.share }}
        TOKEN: ${{ inputs.token }}
